### ISSUE TITLE
Feature request: Minimum player

### ISSUE THREAD

**Issue by benda95280** [GamakCZ/Dragons#1]
First thing, a big thanks for your work !

Could you add option for minimum players ?

Thanks.

**Comment by GamakCZ** [comment]
I forget move it to config

**Comment by GamakCZ** [comment]
https://github.com/GamakCZ/Dragons/blob/master/Dragons/src/vixikhd/dragons/arena/ArenaScheduler.php#L26

Here you can edit it

**Comment by benda95280** [comment]
Any chance to have an update ? :p

**Comment by Johnsonk79** [comment]
Just edit source

**Comment by benda95280** [comment]
NP i've done a pull request :)

**Comment by Johnsonk79** [comment]
Nice
