### ISSUE TITLE
Problems with plugin use

### ISSUE THREAD

**Issue by curtishdev** [GamakCZ/Dragons#11]
Hi! I have a problem with your plugin, it doesn't have auto start
When I have 2/2 players scoreboard don't change. Pls fix auto start and scoreboards Thx! ;)

**Comment by kostamax27** [comment]
> Hi! I have a problem with your plugin, it doesn't have auto start When I have 2/2 players scoreboard don't change. Pls fix auto start and scoreboards Thx! ;)

Look in the file config.yml there specify the minimum number of players to start the game
