### ISSUE TITLE
Pls nevím jak mám stáhnout tvůj bezva plugin :(

### ISSUE THREAD

**Issue by TeiBri** [GamakCZ/Dragons#13]
Vždycky když jsem na poggit.pmmp.io tak jsem ten plugin stáhl v souboru .phar a já potřebuji .jar 
Prosím jestli bys mi nepomohl :)) Jsem noob tak prosím :)))))

Vím že jsi CZ tak konečně nemusím psát v angličtině :)

**Comment by TeiBri** [comment]
Pokud máš automatický překlad a máš ho nastavený na češtinu tak to přepni na angličtinu jinak ten problém nedává smysl xD

**Comment by GamakCZ** [comment]
Plugin je napsanej v jazyce php a ten vypadá úplně jinak než jazyk java pro kterej plugin potřebuješ. Tenhle plugin je udělanej pro server software PocketMine kterej je taky napsanej v phpčku... Tudíž je s pluginem kompatibilní. Jestli chceš tenhle plugin na mc: java server, použij k němu i plugin BigBrother, který ti umožní připojit se na server z mc: java edition.
