### ISSUE TITLE
Restart of the server: Arena not back

### ISSUE THREAD

**Issue by benda95280** [GamakCZ/Dragons#2]
Dear,

After a restart of the server, arena are not taken back :
![Minecraft 19_05_2020 23_32_21](https://user-images.githubusercontent.com/1539408/82380797-59d9bd00-9a29-11ea-96ac-660c1c1439a1.png)

Version PocketMine: 3.12.2

**Comment by GamakCZ** [comment]
You must restart server using /stop command, not using minehub restart button. It's bugged.

**Comment by benda95280** [comment]
Arena seems to not be saved at all, or only when shutdown gracefully initiated.
Why not add here :
https://github.com/GamakCZ/Dragons/blob/e3814c6be460bb893b9720d7394e0e33f8cbd163/Dragons/src/vixikhd/dragons/Dragons.php#L391

`$this->saveArenas();`

Thanks :)
